### ISSUE TITLE
Problem: @reboot not working

### ISSUE THREAD

**Issue by torreyatcitty** [c-rack/quantum-elixir#253]
## Config

```
config :bazaar, Bazaar.Scheduler,
  jobs: [
    {"@reboot", {Bazaar.CronController, :health, []}},
    {"0 12 * * *", {Bazaar.CronController, :daily_inventory_email_task, []}}
  ],
  default_overlaps: false
```

## Output

```
[error] Task #PID<0.3525.0> started from Bazaar.Scheduler.Runner terminating
** (RuntimeError) Special identifier @reboot is not supported.
    (crontab) lib/crontab/date_checker.ex:29: Crontab.DateChecker.matches_date?/2
    (quantum) lib/quantum/executor.ex:44: Quantum.Executor.execute_task_if_date_matches/2
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &Quantum.Executor.execute/2
```

Changing `@reboot` to another special expression ie:`@minutely` works fine. Just `@reboot` doesn't seem to execute and throw this error.

## Version

 - `v2.0.*`
 - in `v2.1.*` this issue was fixed with the refactoring

**Comment by maennchen** [comment]
Fixed with #254, release with `v2.0.3`
