### ISSUE TITLE
Problem: 2.0.3 no function clause matching in Quantum.Executor.execute/2

### ISSUE THREAD

**Issue by crododile** [c-rack/quantum-elixir#257]
starting the app fails with the below error, switched to 2.0.2 and working fine
~~~
[error] Task #PID<0.396.0> started from #PID<0.395.0> terminating
** (FunctionClauseError) no function clause matching in Quantum.Executor.execute/2
    (quantum) lib/quantum/executor.ex:23: Quantum.Executor.execute({~e[* * * * * *], {IO, :inspect, [:beep]}, "America/Los_Angeles"}, %{jobs: [nil: %Quantum.Job{name: nil, overlap: true, pids: [], run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[* * * * * *], state: :active, task: {IO, :inspect, [:beep]}, timezone: "America/Los_Angeles"}], opts: [jobs: [nil: %Quantum.Job{name: nil, overlap: true, pids: [], run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[* * * * * *], state: :active, task: {IO, :inspect, [:beep]}, timezone: "America/Los_Angeles"}], task_supervisor: Meru.Scheduler.Task.Supervisor, runner: {:global, Meru.Scheduler.Runner}, cron: [], timeout: 5000, schedule: nil, overlap: true, run_strategy: {Quantum.RunStrategy.Random, :cluster}, global: true, timezone: "America/Los_Angeles", name: Meru.Scheduler, otp_app: :meru, quantum: Meru.Scheduler]})
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &Quantum.Executor.execute/2
    Args: [{~e[* * * * * *], {IO, :inspect, [:beep]}, "America/Los_Angeles"}, %{jobs: [nil: %Quantum.Job{name: nil, overlap: true, pids: [], run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[* * * * * *], state: :active, task: {IO, :inspect, [:beep]}, timezone: "America/Los_Angeles"}], opts: [jobs: [nil: %Quantum.Job{name: nil, overlap: true, pids: [], run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[* * * * * *], state: :active, task: {IO, :inspect, [:beep]}, timezone: "America/Los_Angeles"}], task_supervisor: Meru.Scheduler.Task.Supervisor, runner: {:global, Meru.Scheduler.Runner}, cron: [], timeout: 5000, schedule: nil, overlap: true, run_strategy: {Quantum.RunStrategy.Random, :cluster}, global: true, timezone: "America/Los_Angeles", name: Meru.Scheduler, otp_app: :meru, quantum: Meru.Scheduler]}]
~~~

~~~
config :meru, Meru.Scheduler,
  global: true,
  timezone: "America/Los_Angeles",
  jobs: [
    {"* * * * *", {IO, :inspect, [:beep]}}]
~~~

~~~
defmodule Meru.Scheduler do
    use Quantum.Scheduler,
        otp_app: :meru
end
~~~

~~~
defmodule Merudo
  use Application
  import Supervisor.Spec

  def start(_type, _args) do
    children = [
      worker(Meru.Scheduler, [])
    ]
    opts = [strategy: :rest_for_one, name: Meru.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
~~~

**Comment by juanazam** [comment]
I'm experiencing the same issue, but even though I see this error, the task performs correctly with the proper timing.

**Comment by maennchen** [comment]
I've identified and will create a PR shortly.

**Comment by maennchen** [comment]
Release `v2.0.4` will be created shortly containing the fix.
