### ISSUE TITLE
Application fails to start after upgrade to 2.1.0

### ISSUE THREAD

**Issue by benrom** [c-rack/quantum-elixir#263]
My app was working fine with 2.0.4, then I upgraded to 2.1.0 and now my app stops at startup:

```elixir
Application romy exited: exited in: Romy.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (KeyError) key :runner not found in: [task_supervisor: Romy.Scheduler.Task.Supervisor, task_registry: Romy.Scheduler.TaskRegistry, executor_supervisor: Romy.Scheduler.ExecutorSupervisor, execution_broadcaster: Romy.Scheduler.ExecutionBroadcaster, job_broadcaster: Romy.Scheduler.JobBroadcaster, global: false, cron: [], timeout: 5000, schedule: nil, overlap: true, timezone: :utc, run_strategy: {Quantum.RunStrategy.Random, :cluster}, otp_app: :romy, quantum: Romy.Scheduler]
            (elixir) lib/keyword.ex:371: Keyword.fetch!/2
            (romy) lib/romy/tasks/scheduler.ex:3: Romy.Scheduler.add_job/1
            (romy) lib/romy.ex:76: Romy.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
Application quantum exited: :stopped
Application crontab exited: :stopped
```

Here's my scheduler:
```elixir
defmodule Romy.Scheduler do
  # Quantum job scheduler
  use Quantum.Scheduler, otp_app: :romy
end
```

My app start function:
```elixir
def start(_type, _args) do
  import Supervisor.Spec, warn: false
  alias Quantum.Job
  alias Romy.Scheduler
  import Crontab.CronExpression

  children = [
  # ...
    worker(Romy.Scheduler, [])
  ]

  opts = [strategy: :one_for_one, name: Romy.Supervisor]
  app = Supervisor.start_link(children, opts)

  Scheduler.new_job()
  |> Job.set_name(:monitor_beam)
  |> Job.set_task({Shared.Monitor, :beam, []})
  |> Job.set_schedule(~e[* * * * *])
  |> Scheduler.add_job()
end
```

What do I need to change to fix this crash?

**Comment by maennchen** [comment]
@benrom Could you please try to do a `mix.clean` and compile again? I don't see any references to the old runner anymore.

**Comment by benrom** [comment]
You were right, a good clean did fix it.
Thanks!

**Comment by maennchen** [comment]
@benrom Great, I was already worried how such a big bug could slip through into a stable release :P
