### ISSUE TITLE
Problem: when a task raises an error, other jobs disappear

### ISSUE THREAD

**Issue by papylhomme** [c-rack/quantum-elixir#86]
Everything is in the title ;)

Here is a test case illustrating this issue: 

EDIT: just to be clear, module ```Test``` doesn't exists, it's the point. Tested against v1.6.1

```elixir
iex(1)> Application.start :quantum
:ok
iex(2)> Quantum.jobs
[]
iex(3)> Quantum.add_job(:hourly, %Quantum.Job{schedule: "@hourly", task: {Test, :call1}, args: []})
:ok
iex(4)> Quantum.jobs
[hourly: %Quantum.Job{args: [], name: :hourly, nodes: [:nonode@nohost],
  overlap: true, pid: nil, schedule: "@hourly", state: :active,
  task: {Test, :call1}}]
iex(5)> Quantum.add_job(:minutly, %Quantum.Job{schedule: "* * * * *", task: {Test, :call1}, args: []})
:ok
iex(6)> Quantum.jobs
[minutly: %Quantum.Job{args: [], name: :minutly, nodes: [:nonode@nohost],
  overlap: true, pid: nil, schedule: "* * * * *", state: :active,
  task: {Test, :call1}},
 hourly: %Quantum.Job{args: [], name: :hourly, nodes: [:nonode@nohost],
  overlap: true, pid: #PID<0.71.0>, schedule: "@hourly", state: :active,
  task: {Test, :call1}}]
iex(7)>
16:51:00.518 [error] Task #PID<0.74.0> started from Quantum terminating
** (UndefinedFunctionError) undefined function Test.call1/0 (module Test is not available)
    Test.call1()
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &Quantum.Executor.execute/2
    Args: [{"* * * * *", {Test, :call1}, []}, %{d: {2016, 3, 9}, h: 15, jobs: [minutly: %Quantum.Job{args: [], name: :minutly, nodes: [:nonode@nohost], overlap: true, pid: nil, schedule: "* * * * *", state: :active, task: {Test, :call1}}, hourly: %Quantum.Job{args: [], name: :hourly, nodes: [:nonode@nohost], overlap: true, pid: #PID<0.71.0>, schedule: "@hourly", state: :active, task: {Test, :call1}}], m: 51, r: 0, w: 3}]

nil
iex(8)> Quantum.jobs
[]
```

**Comment by c-rack** [comment]
@papylhomme Could you please try current master branch? We have recently solved #82, but not released a new version yet. If you can confirm that current master solves the problem you described, I will release a new version shortly.

**Comment by papylhomme** [comment]
My bad, I didn't look well enough for an existing issue !  The problem is indeed fixed in master branch. 

Regarding the new release, AFAIC I'm not in a hurry, I just wrapped the task in my own module in order to provide feedback, so this isn't blocking.

Closing now.

**Comment by c-rack** [comment]
OK, thanks.

Anyhow, I'll prepare a new release; it's long overdue :-)

**Comment by c-rack** [comment]
Version 1.7.0 has been released, including the bugfix for this issue.
